<a href="https://colab.research.google.com/github/ignyz/Numerical-methods-and-algorithms/blob/main/L2_1_TiesiniuLygciuSprendimas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://i.ibb.co/981WQxd/1uzd.png)
![alt text](https://i.imgur.com/bN7Y61G.png)



In [ ]:
#!/usr/bin/python
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt
import math

# veiksmai su matricomis (tiesine algebra)
A = [[3, 7, 1, 3],
     [1, -6, 6, 8], 
     [4, 4, -7, 1],
     [-1, 3, 8, 2]]
print("Determinantas: ",np.linalg.det(A))
print("Determinantas yra labai arti 0 tai galima sakyti kad sprendiniu nera")
A = np.array([[3., 7., 1., 3.], [1., -6., 6., 8.], [4., 4., -7., 1.],
             [-1., 3., 8., 2.]])

A = np.array([[3., 7., 1., 3.], 
              [1., -6., 6., 8.],
              [4., 4., -7., 1.],
             [-1., 3., 8., 6.]])

#A = np.array([[  1.,   0.,   0.,   0.,   0.,   0.],
# [  1.,   1.,   0.,   0.,   0.,   0.],
# [  1.,   2.,   2.,   0.,   0.,   0.],
# [  1.,  3.,   6. ,  6. ,  0. ,  0.],
# [  1. ,  4. , 12. , 24.,  24. ,  0.],
# [  1. ,  5. , 20. , 60. ,120. ,120.]])

b = np.array([[11.], [3.], [1.], [1.]])# print(A)#
#b = np.array([[-7.31342548e-04], [-9.13551146e-02], [-1.47129365e+00], [-3.00000000e+00],
 #[-7.35646823e-01] ,[-1.82710229e-02]])
#print(b)
n = A.shape[1]
nb = b.shape[1]#print(nb)#print(n)
print(b[1])
A1 = np.hstack((A, b))#print(A1)
for i in range(0, n-1):
    for j in range(i + 1, n):        #A1(j,i+1:n+nb)=A1(j,i+1:n+nb)-A1(i,i+1:n+nb)*A1(j,i)/A1(i,i);
        A1[j, i + 1:n + nb] = A1[j, i + 1:n + nb] - (A1[i, i + 1:n + nb] * A1[j, i]) / A1[i, i]
        A1[j, i] = 0
    print("\n",i,":--------------------------------------------------------------\n")
    print(A1)
s = (n, nb)
x=np.zeros(s)
x[n-1] =(A1[n-1,n])/A1[n-1,n-1] 
for i in range(n-1,-1,-1):
  k= 0
  for j in range(i+1,n):
    k = k + (A1[i,j]*x[j])
  x[i] =(A1[i,n]-k)/A1[i,i]
if not math.isnan(x[0]):
  print("Sprendinys x=\n", x)  
  liekana = np.matmul(A,x)-b
  print("Sprendinio patikrinimas:\n", liekana )
  print("Bendra santykine paklaida:\n",np.linalg.norm(liekana)/np.linalg.norm(x))
  print(np.linalg.det(A))
else:
  print("Sprendinių nėra kadangi 0 != 9")

Determinantas:  2.655653474903371e-13
Determinantas yra labai arti 0 tai galima sakyti kad sprendiniu nera
[3.]

 0 :--------------------------------------------------------------

[[  3.           7.           1.           3.          11.        ]
 [  0.          -8.33333333   5.66666667   7.          -0.66666667]
 [  0.          -5.33333333  -8.33333333  -3.         -13.66666667]
 [  0.           5.33333333   8.33333333   7.           4.66666667]]

 1 :--------------------------------------------------------------

[[  3.           7.           1.           3.          11.        ]
 [  0.          -8.33333333   5.66666667   7.          -0.66666667]
 [  0.           0.         -11.96        -7.48       -13.24      ]
 [  0.           0.          11.96        11.48         4.24      ]]

 2 :--------------------------------------------------------------

[[  3.           7.           1.           3.          11.        ]
 [  0.          -8.33333333   5.66666667   7.          -0.66666667]